### ISSUE TITLE
Decide if the functions in the ```__init__.py``` of the testbed_example config folder should be moved into catkit2 package

### ISSUE THREAD

**Issue by erinpougheon** [spacetelescope/catkit2#227]
While creating the testbed_example folder to have a simple example of use with just a camera, I created into the ```config``` folder a file called ```__init__.py```.
It is needed to decide either the functions in that file need to be moved into the catkit2 package or if they have to stay here.

**Comment by ivalaginja** [comment]
This is coming out of #226.

**Comment by ivalaginja** [comment]
Not needed anymore.
