### ISSUE TITLE
Create a Fourier Transform Viewer

### ISSUE THREAD

**Issue by erinpougheon** [spacetelescope/catkit2#230]
Based on #226 
We want to create a new viewer, called 'FT Viewer'. Can be accessed by the context menu (right click on the layout).
On this viewer, we want to have a context menu to choose the camera on which we want to have this viewer.
On this viewer, we want to have a frame of the camera, as in the camera viewer, with the possibility to stop acquisition etc as in the camera viewer.
We also want to have a viewer of the FT module.
Below those two viewers, we want to have a curve of the pixels that can be choosen with a cross that we can move on the camera or FT viewer. Each plot will have 2 curves (on for the y axis, one for the x axis), and there will have 2 of these plots (one under the camera frame, one under the FT module frame).

**Comment by ivalaginja** [comment]
Not needed anymore.
