### ISSUE TITLE
`actuator_grid` in new DM proxy is 1D because dimension reading returns tuple

### ISSUE THREAD

**Issue by ivalaginja** [spacetelescope/catkit2#253]
https://github.com/spacetelescope/catkit2/blob/cd43bbc7c6e3d86bce08abfea86fe26bef08e9cd/catkit2/testbed/proxies/deformable_mirror.py#L51

The variable `dims` contains only one number, so `hcipy.make_uniform_grid()` returns a 1D grid in the case of THD2.

This works fine in the HiCAT case since the tuple contains the correct dimensions from the input file on. On THD2, we're missing the dimension indicating the number of DMs controlled with one service.

@ehpor Is the solution to add an extra dimension in my fits files? Is this possible? Or to put back in some of the dimension extensions that we deleted when working on the DM base class PR?

**Comment by ivalaginja** [comment]
Yes I can save files like that. It just makes my Boston viewer a mess.

Can be closed, thanks for being my rubber ducky 🦆

**Comment by ehpor** [comment]
Yep, adding extra dimensions is indeed possible. 😆
