### ISSUE TITLE
Logging timestamps as default

### ISSUE THREAD

**Issue by lanemeier7** [spacetelescope/catkit2#267]
Logging timestamps are useful references for experiments that run over long periods of time and trouble shooting between processes. It would be nice to configure catkit2's default to have timestamps for all log messages.

**Comment by ehpor** [comment]
Timestamps are saved in the log files, but not printed in the testbed terminal. Honestly, the testbed terminal print was a debug print that I never bothered to remove. 😅

**Comment by lanemeier7** [comment]
I haven't been able to find the log files. Where do they get saved?

**Comment by ehpor** [comment]
There are stored in the experiment folder, alongside the experiment metadata file and all output files from that experiment. The experiment folders are inside the `testbed.base_data_path`, the value of which is taken from the `testbed.yml` config file.

**Comment by lanemeier7** [comment]
This was all a misunderstanding on my part. All log stamps are logged via the `LogWriter` class that is part of `Experiment`. In my test scripts where I was only using `ServiceProxy`'s and `TestBeds` I did not see this
