### ISSUE TITLE
Warnings during compilation in MacOS

### ISSUE THREAD

**Issue by ehpor** [spacetelescope/catkit2#72]
From @asahooexo in https://github.com/spacetelescope/hicat-package2/issues/88

> I ran "python setup.py develop" after updating catkit2 conda environment in my local machine. And I got bunch of warnings during compilation. Copy pasting the terminal output:
> 
> ```
> running develop
> /opt/miniconda3/envs/catkit2/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
>   EasyInstallDeprecationWarning,
> /opt/miniconda3/envs/catkit2/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
>   setuptools.SetuptoolsDeprecationWarning,
> running egg_info
> writing catkit2.egg-info/PKG-INFO
> writing dependency_links to catkit2.egg-info/dependency_links.txt
> writing top-level names to catkit2.egg-info/top_level.txt
> adding license file 'LICENSE.rst'
> writing manifest file 'catkit2.egg-info/SOURCES.txt'
> running build_ext
> Compiling protobuffers...
> -- Found Protobuf: /opt/miniconda3/envs/catkit2/lib/libprotobuf.dylib (found version "3.20.1") 
> -- pybind11 v2.10.0 dev1
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /Users/asahoo/repos/catkit2/build/temp.macosx-10.9-x86_64-3.7
> Consolidate compiler generated dependencies of target catkit_core
> [  3%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/DataStream.cpp.o
> [  6%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/SharedMemory.cpp.o
> [ 10%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/Synchronization.cpp.o
> [ 13%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/Timing.cpp.o
> [ 17%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/Log.cpp.o
> [ 20%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/LogConsole.cpp.o
> [ 24%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/LogFile.cpp.o
> [ 27%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/LogForwarder.cpp.o
> [ 31%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/HostName.cpp.o
> [ 34%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/Command.cpp.o
> [ 37%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/Property.cpp.o
> [ 41%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/Service.cpp.o
> [ 44%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/Server.cpp.o
> [ 48%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/Client.cpp.o
> [ 51%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/TestbedProxy.cpp.o
> [ 55%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/ServiceProxy.cpp.o
> [ 58%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/ServiceState.cpp.o
> [ 62%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/Tensor.cpp.o
> [ 65%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/TracingProxy.cpp.o
> [ 68%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/Types.cpp.o
> [ 72%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/Util.cpp.o
> [ 75%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/proto/core.pb.cc.o
> [ 79%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/proto/logging.pb.cc.o
> [ 82%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/proto/testbed.pb.cc.o
> [ 86%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/proto/service.pb.cc.o
> [ 89%] Building CXX object catkit_core/CMakeFiles/catkit_core.dir/proto/tracing.pb.cc.o
> [ 93%] Linking CXX static library libcatkit_core.a
> [ 93%] Built target catkit_core
> Consolidate compiler generated dependencies of target catkit_bindings
> [ 96%] Building CXX object catkit_bindings/CMakeFiles/catkit_bindings.dir/bindings.cpp.o
> [100%] Linking CXX shared module catkit_bindings.cpython-37m-darwin.so
> ld: warning: direct access in function 'nlohmann::detail::iter_impl<nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > const>::operator*() const' from file 'CMakeFiles/catkit_bindings.dir/bindings.cpp.o' to global weak symbol 'typeinfo for nlohmann::detail::invalid_iterator' from file '../catkit_core/libcatkit_core.a(TestbedProxy.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'nlohmann::detail::iter_impl<nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > const>::operator*() const' from file 'CMakeFiles/catkit_bindings.dir/bindings.cpp.o' to global weak symbol 'typeinfo for nlohmann::detail::invalid_iterator' from file '../catkit_core/libcatkit_core.a(TestbedProxy.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'nlohmann::detail::iter_impl<nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > const>::key() const' from file 'CMakeFiles/catkit_bindings.dir/bindings.cpp.o' to global weak symbol 'typeinfo for nlohmann::detail::invalid_iterator' from file '../catkit_core/libcatkit_core.a(TestbedProxy.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'void nlohmann::detail::from_json<nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > >(nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > const&, nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > >::boolean_t&)' from file 'CMakeFiles/catkit_bindings.dir/bindings.cpp.o' to global weak symbol 'typeinfo for nlohmann::detail::type_error' from file '../catkit_core/libcatkit_core.a(LogForwarder.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'void nlohmann::detail::get_arithmetic_value<nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > >, long long, 0>(nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > const&, long long&)' from file 'CMakeFiles/catkit_bindings.dir/bindings.cpp.o' to global weak symbol 'typeinfo for nlohmann::detail::type_error' from file '../catkit_core/libcatkit_core.a(LogForwarder.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'void nlohmann::detail::get_arithmetic_value<nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > >, double, 0>(nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > const&, double&)' from file 'CMakeFiles/catkit_bindings.dir/bindings.cpp.o' to global weak symbol 'typeinfo for nlohmann::detail::type_error' from file '../catkit_core/libcatkit_core.a(LogForwarder.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'void nlohmann::detail::from_json<nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > >(nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > const&, nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > >::string_t&)' from file 'CMakeFiles/catkit_bindings.dir/bindings.cpp.o' to global weak symbol 'typeinfo for nlohmann::detail::type_error' from file '../catkit_core/libcatkit_core.a(LogForwarder.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'nlohmann::detail::iter_impl<nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > const>::operator==(nlohmann::detail::iter_impl<nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > const> const&) const' from file 'CMakeFiles/catkit_bindings.dir/bindings.cpp.o' to global weak symbol 'typeinfo for nlohmann::detail::invalid_iterator' from file '../catkit_core/libcatkit_core.a(TestbedProxy.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'std::__1::__shared_ptr_pointer<DataStream*, std::__1::shared_ptr<DataStream>::__shared_ptr_default_delete<DataStream, DataStream>, std::__1::allocator<DataStream> >::__get_deleter(std::type_info const&) const' from file 'CMakeFiles/catkit_bindings.dir/bindings.cpp.o' to global weak symbol 'typeinfo name for std::__1::shared_ptr<DataStream>::__shared_ptr_default_delete<DataStream, DataStream>' from file '../catkit_core/libcatkit_core.a(DataStream.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> [100%] Built target catkit_bindings
> -- Install configuration: "Release"
> -- Installing: /Users/asahoo/repos/catkit2/build/lib/libcatkit_core.a
> -- Up-to-date: /Users/asahoo/repos/catkit2/build/include/catkit_core
> -- Up-to-date: /Users/asahoo/repos/catkit2/build/include/catkit_core/LogFile.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/Client.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/proto
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/proto/service.pb.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/proto/logging.pb.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/proto/testbed.pb.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/proto/core.pb.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/proto/tracing.pb.h
> -- Up-to-date: /Users/asahoo/repos/catkit2/build/include/catkit_core/ComplexTraits.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/LoggingProxy.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/Types.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/Service.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/Timing.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/Synchronization.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/Tensor.inl
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/ServiceState.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/LogForwarder.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/DataStream.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/SharedMemory.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/TracingProxy.h
> -- Up-to-date: /Users/asahoo/repos/catkit2/build/include/catkit_core/Log.h
> -- Up-to-date: /Users/asahoo/repos/catkit2/build/include/catkit_core/HostName.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/Util.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/Util.inl
> -- Up-to-date: /Users/asahoo/repos/catkit2/build/include/catkit_core/LogConsole.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/ServiceProxy.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/Command.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/TestbedProxy.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/Property.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/Server.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/Finally.h
> -- Installing: /Users/asahoo/repos/catkit2/build/include/catkit_core/Tensor.h
> -- Installing: /Users/asahoo/repos/catkit2/build/lib/catkit_bindings.cpython-37m-darwin.so
> Creating /opt/miniconda3/envs/catkit2/lib/python3.7/site-packages/catkit2.egg-link (link to .)
> catkit2 0.0.1 is already the active version in easy-install.pth
> 
> Installed /Users/asahoo/repos/catkit2
> Processing dependencies for catkit2==0.0.1
> Finished processing dependencies for catkit2==0.0.1
> ```

@ehpor said:

> This seems like a common problem (if I believe a quick google search). Possible causes:
> 
> differing C++ standards between catkit_core and catkit_bindings. This is easy to fix.
> wrong DLL export qualifications. This is impossible to fix, since some of the warnings are internal in external dependencies.
> Possible solution:
> 
> add -fvisibility=default command line argument to the compiler on MacOS. This will force all symbols to be exported. This will also increase the size of the symbol library, which is generally undesirable.
> Will need to investigate further.

Transferred to the catkit2 repo as it has to do with catkit2 compilation, not hicat-package2.

**Comment by raphaelpclt** [comment]
These warnings seems to have disappeared. One other warning remains but out of scope for this issue.
